### ISSUE TITLE
Notification and Request for Review of Forked Project `lens-extension-fluxcd`

### ISSUE THREAD

**Issue by okaufmann** [appvia/lens-extension-fluxcd#4]
Hi @sponte,

I've forked `lens-extension-fluxcd` to [okaufmann/lens-extension-fluxcd](https://github.com/okaufmann/lens-extension-fluxcd) to continue its development. The original license is retained, and all efforts have been made to respect the project's guidelines.

If there are any concerns regarding the fork or if it doesn't align with the original terms, please let me know. Your input would be greatly appreciated.

Best regards,
Oliver

**Comment by sponte** [comment]
Hello @okaufmann 

Thank you for reaching out. Glad you've taken the interest in the extension. 

Apologies for the delay. I just noticed the issue you've raised previously and the PR. My notifications were sent to the spam so wasn't aware of this effort. 

I would be happy to review and pull your changes into our project if you'd like unless you prefer to continue with your own fork?

Kind regards
Stan

**Comment by okaufmann** [comment]
@sponte If you could merge my two open PRs I can then PR all the other changes I made. I suggest you take a look at what I changed and tell me if we should bring this back into this project.

**Comment by sponte** [comment]
Hello @okaufmann 

Thanks for the probe. I have merged the scrolling fix and released v0.0.7 with Lens v6 support. 

Hope it helps.

Stan
